### ISSUE TITLE
Improve handling of Replica-lines

### ISSUE THREAD

**Issue by peterzeller** [AntidoteDB/crdt-visualizer#3]
Currently, it is necessary to precisely hit the replica lines for showing tooltips or for drawing lines. It should be enough to get within 10px or so of the line.

**Comment by frikhayessine** [comment]
- [x] Improve handling of Replica-lines for drawing the update

- [x]  Improve handling of Replica-lines for showing tooltips

**Comment by frikhayessine** [comment]
it is no more necessary to precisely hit the replica lines for showing tooltips or for drawing line. Shall we close this issue ?
